export const DATABASE_ERRORS = {
  UNIQUE_CONSTRAINT: 'P2002',
  RECORD_NOT_FOUND: 'P2025',
  INVALID_DATA: 'P2014',
} as const;

export const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'AUTH001',
  TOKEN_EXPIRED: 'AUTH002',
  INVALID_TOKEN: 'AUTH003',
  UNAUTHORIZED: 'AUTH004',
} as const;

export const VALIDATION_ERRORS = {
  INVALID_INPUT: 'VAL001',
  MISSING_FIELD: 'VAL002',
  INVALID_FORMAT: 'VAL003',
} as const;

export const BUSINESS_ERRORS = {
  RESOURCE_NOT_FOUND: 'BUS001',
  INSUFFICIENT_PERMISSIONS: 'BUS002',
  INVALID_OPERATION: 'BUS003',
} as const;
